### PR TITLE
Fix #25: stop Subprocess::Process#communicate from leaking open FDs.

### LINKED ISSUE #25: Subprocess 'leaks' open FDs until the Process objects are garbage-collected
While using the subprocess module to execute some fairly simple commands, I noticed that my script was using _far_ more FDs than it should have been (50+, when it should have been <= 10). It took me quite a while to track down -- the problem is that Subprocess::Process#communicate opens an IO.pipe that is never closed (until the GC closes it when the Process object is collected).

I was able to fix the issue by adding:

```ruby
self_read.close
self_write.close
```

... on lines 426 and 427 of subprocess.rb, directly after the `end` of the `self.class.catching_sigchld(pid, self_write)` block (on GitHub current master, this is line 429: https://github.com/stripe/subprocess/blob/master/lib/subprocess.rb#L429 ).

AFAICT this shouldn't have any effect on the overall operation of the class, but it does help keep the number of the FDs that the script has open down and more representative of what is actually in-use.

Could we get this change rolled into the subprocess module, please?

### PR DESCRIPTION
**Pull request by rbroemeling**

### CODE REVIEW

**Comment by andrew-stripe** [comment]
@rbroemeling: What do you think about an implementation where `catching_sigchld` invokes the block form of `IO.pipe` and yields the read side to the block?

**Comment by rbroemeling** [comment]
@andrew-stripe I'm having trouble imagining a use for that. What's the intention of that implementation?

**Comment by andrew-stripe** [comment]
Just to encapsulate the cleanup logic into `catching_sigchld` rather than forcing the caller to manage it.

**Comment by rbroemeling** [comment]
@andrew-stripe Sure, I think that makes sense.

**Comment by russelldavis** [comment]
> What do you think about an implementation where catching_sigchld invokes the block form of IO.pipe and yields the read side to the block?

I implemented the fix in that form at #31

**Comment by andrew-stripe** [comment]
Fixed in #33

**Pull request closed without merging**
