### PR TITLE
Remove support for Ruby 1.8

### PR DESCRIPTION
**Pull request by zenazn**

### CODE REVIEW

**Comment by zenazn** [comment]
Not sure why tests aren't running on `osx`, but don't really want to debug it (tests pass locally on `1.9.3` and `2.1`)

r? @nelhage or @ebroder

**Comment by zenazn** [comment]
This also incidentally fixes #11

**Comment by ebroder** [comment]
LGTM

**Comment by ab** [comment]
@zenazn OS X tests on Travis are in private beta, and they're not currently adding new repos. (I want it for rest-client, too.)

**Comment by ab** [comment]
Oh btw, Travis actually has since added rest-client to the OS X beta, so you might be able to get subprocess in as well!

**Pull request merged**
